@startuml

hide circle

entity "User" {
  *user_id
  *user_name
}

entity "Question" {
  *question_id
  *user_id
  *question_title
}

entity "QuestionStatus" {
  *question_status_id
  *question_id
  *complete
  *in_complete
}

User||--{Question
Question||--||QuestionStatus

@enduml