@startuml

hide circle

entity "User" {
  *user_id
  *user_name
}

entity "Question" {
  *question_id
  *user_id
  *question_status_id
  *question_title
}

entity "QuestionStatus" {
  *question_status_id
  *status
}

User}--{Question
Question||--||QuestionStatus

@enduml